fixtures:
  repositories:
    'cinder':
      repo: 'git://github.com/enovance/puppet-cinder'
      ref: 'origin/stable/havana'
    'keystone':
      repo: 'git://github.com/enovance/puppet-keystone.git'
      ref: 'origin/stable/havana'
    'nova':
      repo: 'git://github.com/enovance/puppet-nova.git'
      ref: 'origin/stable/havana'
    'glance':
      repo: 'git://github.com/enovance/puppet-glance.git'
      ref: 'origin/stable/havana'
    'horizon':
      repo: 'git://github.com/enovance/puppet-horizon'
      ref: 'origin/stable/havana'
    'swift':
      repo: 'git://github.com/enovance/puppet-swift'
      ref: 'origin/stable/havana'
    'neutron':
      repo: 'git://github.com/enovance/puppet-neutron'
      ref: 'origin/stable/havana'
    'ceilometer':
      repo: 'git://github.com/enovance/puppet-ceilometer'
      ref: 'origin/stable/havana'
    'heat':
      repo: 'git://github.com/enovance/puppet-heat'
      ref: 'origin/stable/havana'
    'apt': 'git://github.com/enovance/puppetlabs-apt.git'
    'apache': 'git://github.com/enovance/puppetlabs-apache.git'
    'ceph': 'git://github.com/enovance/puppet-ceph.git'
    'concat': 'git://github.com/enovance/puppet-concat.git'
    'haproxy': 'git://github.com/enovance/puppetlabs-haproxy.git'
    'keepalived': 'git://github.com/enovance/puppet-module-keepalived.git'
    'mongodb': 'git://github.com/enovance/puppetlabs-mongodb.git'
    'mysql':
      repo: 'git://github.com/enovance/puppetlabs-mysql.git'
      ref: 'origin/0.x'
    'rabbitmq':
      repo: 'git://github.com/enovance/puppetlabs-rabbitmq'
      ref: 'origin/2.x'
    'memcached': 'git://github.com/enovance/puppet-memcached'
    'ntp': 'git://github.com/enovance/puppetlabs-ntp.git'
    'sysctl': 'git://github.com/enovance/puppet-sysctl.git'
    'inifile':  'git://github.com/enovance/puppetlabs-inifile'
    'vswitch': 'git://github.com/enovance/puppet-vswitch'
    'tempest': 'git://github.com/enovance/puppet-tempest'
    'vcsrepo': 'git://github.com/enovance/puppetlabs-vcsrepo'
    'stdlib': 'git://github.com/enovance/puppetlabs-stdlib.git'
    'xinetd': 'git://github.com/enovance/puppetlabs-xinetd.git'
    'rhnreg_ks': 'git://github.com/enovance/puppet-rhnreg_ks.git'
  symlinks:
    'cloud': '#{source_dir}'
