fixtures:
  repositories:
    'cinder':
      repo: 'git://github.com/enovance/puppet-cinder'
      ref: '504a061918ac08297f6a9b9f64f1836643573447'
    'keystone':
      repo: 'git://github.com/enovance/puppet-keystone.git'
      ref: 'd9aac2f78240e0fd651a6dc0ac05db4ffcba885b'
    'nova':
      repo: 'git://github.com/enovance/puppet-nova.git'
      ref: '47d576d2e62b4c449309ef228cdbc17bcf3fdcf0'
    'glance':
      repo: 'git://github.com/enovance/puppet-glance.git'
      ref: 'e61e47d664e4d18e849bc7c3d5f40f452397d0f4'
    'horizon':
      repo: 'git://github.com/enovance/puppet-horizon'
      ref: 'da0cedce6f14f5c35e733ac345d8d862db11cd2b'
    'swift':
      repo: 'git://github.com/enovance/puppet-swift'
      ref: '9b60581a1c8fd2c1a98adafc1bcdc53796859e23'
    'neutron':
      repo: 'git://github.com/enovance/puppet-neutron'
      ref: '78428c844f73bf585a8f8a3bdf615ba2a0e8983b'
    'ceilometer':
      repo: 'git://github.com/enovance/puppet-ceilometer'
      ref: 'f444fc8937a6bc05d0257c1a935e742491e94b02'
    'heat':
      repo: 'git://github.com/enovance/puppet-heat'
      ref: '2847d4d42fdc413c0297b7aeedc9f29198e336c2'
    'apt':
      repo: 'git://github.com/enovance/puppetlabs-apt.git'
      ref: '9b001af8775c7231ea2656b7eb43d6141b536f49'
    'apache':
      repo: 'git://github.com/enovance/puppetlabs-apache.git'
      ref: '58682faf74cdfc6c8d921d2be9322368c8a96cf9'
    'ceph':
      repo: 'git://github.com/enovance/puppet-ceph.git'
      ref: 'cc63bacaef2b1d8949777f58e23698e6bbf87f43'
    'concat':
      repo: 'git://github.com/enovance/puppet-concat.git'
      ref: '04356974f72b90a1d0f57346a00e95a717924e43'
    'haproxy':
      repo: 'git://github.com/enovance/puppetlabs-haproxy.git'
      ref: '0d4c50ed56f4fce06b66c04611cebec29f7a37a8'
    'keepalived':
      repo: 'git://github.com/enovance/puppet-module-keepalived.git'
      ref: 'eb345b6d3b25106cbe166028f2b8dd9974a10230'
    'mongodb':
      repo: 'git://github.com/enovance/puppetlabs-mongodb.git'
      ref: 'e3cc9a0ea895f6e01801e4620799c66c2337b7ed'
    'mysql':
      repo: 'git://github.com/enovance/puppetlabs-mysql.git'
      ref: '11ab036fed3b252492f5400bf8fd69698d510482'
    'rabbitmq':
      repo: 'git://github.com/enovance/puppetlabs-rabbitmq'
      ref: '25420cb3c26c9a8432ab519d43c094d614d4fec4'
    'memcached':
      repo: 'git://github.com/enovance/puppet-memcached'
      ref: 'd009260de3c7623003318555ec5ca61217ea3ca1'
    'ntp':
      repo: 'git://github.com/enovance/puppetlabs-ntp.git'
      ref: 'eb02ba2937ce86fb609ae41499767244b78ec58d'
    'sysctl':
      repo: 'git://github.com/enovance/puppet-sysctl.git'
      ref: '4a463384e844f51b270428643a5b8beb3628e854'
    'inifile':
      repo: 'git://github.com/enovance/puppetlabs-inifile'
      ref: 'ae23a4db97d2815ec305d0529912685f07746d3c'
    'vswitch':
      repo: 'git://github.com/enovance/puppet-vswitch'
      ref: '065fadb2d33857cd31f293677de56d18793e1412'
    'stdlib':
      repo: 'git://github.com/enovance/puppetlabs-stdlib.git'
      ref: '224b8f9a191f635b03ee900a9bf87bfdb0f1a6ed'
    'xinetd':
      repo: 'git://github.com/enovance/puppetlabs-xinetd.git'
      ref: '7557af0e418d1a587df04fe7d01322ff2473c32e'
    'rhnreg_ks':
      repo: 'git://github.com/enovance/puppet-rhnreg_ks.git'
      ref: '8fdc051992b44a09f39d3b510d7cd6db5ed5ff66'
    'dnsclient':
      repo: 'git://github.com/enovance/puppet-module-dnsclient.git'
      ref: '4158b30f4660623f98dcdbd1ce9b482556180b57'
    'boolean':
      repo: 'git://github.com/enovance/puppet-boolean.git'
      ref: '157011a4eaa27f1202a9d94335ee4876b26d377e'
    'kmod':
      repo: 'git://github.com/enovance/puppet-kmod.git'
      ref: 'accc40093e6f8ee9cc472e9eb6ba3bab4bad3a1f'
  symlinks:
    'cloud': '#{source_dir}'
