language: ruby
script: "bundle exec rake test COV=y SPEC_OPTS='--format n --color --backtrace'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.0"
notifications:
  email: false
