language: ruby
script: "bundle exec rake test COV=y SPEC_OPTS='--format documentation --color --backtrace'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
notifications:
  email: false
